version: '3'
services:
  postgres:
    image: 'postgres:10'
    security_opt:
      - apparmor=unconfined
  redis:
    image: 'redis:4'
    security_opt:
      - apparmor=unconfined
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app

