version: '3'
services:
  postgres:
    image: 'postgres:10'
    security_opt:
      - apparmor=unconfined
  redis:
    image: 'redis:4'
    security_opt:
      - apparmor=unconfined
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    security_opt:
      - apparmor=unconfined
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

